services:
  edulution-collabora:
    image: collabora/code:latest
    container_name: edulution-collabora
    restart: always
    cap_add:
      - SYS_ADMIN
    expose:
      - "9980"
    environment:
      - aliasgroup1=${EDULUTION_BASE_DOMAIN}
      - extra_params=--o:ssl.enable=false --o:net.service_root=/collabora
