services:
  edulution-onlyoffice-documentserver:
    container_name: edulution-onlyoffice-documentserver
    image: netzint/onlyoffice-documentserver:7.5.0
    depends_on:
      - edulution-onlyoffice-postgresql
      - edulution-onlyoffice-rabbitmq
    restart: always
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - AMQP_URI=amqp://guest:guest@edulution-onlyoffice-rabbitmq
      # - SSL_CERTIFICATE_PATH=/etc/ssl/webserver/tls.crt
      # - SSL_KEY_PATH=/etc/ssl/webserver/tls.key
      # - SSL_DHPARAM_PATH=/etc/ssl/webserver/dhparam.pem
      - REDIS_SERVER_HOST=redis
      - REDIS_SERVER_PORT=6379
      - JWT_ENABLED=true
      - JWT_SECRET=${EDULUTION_ONLYOFFICE_JWT_SECRET}
    volumes:
      - /srv/docker/edulution-ui/data/apps/filesharing/onlyoffice/data:/var/www/onlyoffice/Data
      - /srv/docker/edulution-ui/data/apps/filesharing/onlyoffice/log:/var/log/onlyoffice
      - /srv/docker/edulution-ui/data/apps/filesharing/onlyoffice/lib:/var/lib/onlyoffice
      - /srv/docker/edulution-ui/data/apps/filesharing/onlyoffice/fonts:/usr/share/fonts

  edulution-onlyoffice-rabbitmq:
    container_name: edulution-onlyoffice-rabbitmq
    image: rabbitmq:4
    restart: always

  edulution-onlyoffice-redis:
    container_name: edulution-onlyoffice-redis
    image: redis:7
    restart: always

  edulution-onlyoffice-postgresql:
    container_name: edulution-onlyoffice-postgresql
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=${EDULUTION_ONLYOFFICE_POSTGRES_PASSWORD}
      - JWT_ENABLED=true
      - JWT_SECRET=${EDULUTION_ONLYOFFICE_JWT_SECRET}
    volumes:
      - /srv/docker/edulution-ui/data/apps/filesharing/onlyoffice/db:/var/lib/postgresql
