services:
  edulution-onlyoffice-documentserver:
    container_name: edulution-onlyoffice-documentserver
    image: onlyoffice/documentserver:9.3
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${EDULUTION_ONLYOFFICE_JWT_SECRET}
      - ENABLE_SSL=false
      - DS_BASE_PATH=/docservice/
    restart: always
    volumes:
      - /srv/docker/edulution-ui/data/apps/filesharing/onlyoffice/data:/var/www/onlyoffice/Data
      - /srv/docker/edulution-ui/data/apps/filesharing/onlyoffice/log:/var/log/onlyoffice
      - /srv/docker/edulution-ui/data/apps/filesharing/onlyoffice/lib:/var/lib/onlyoffice
      - /srv/docker/edulution-ui/data/apps/filesharing/onlyoffice/fonts:/usr/share/fonts
    expose:
      - "80"
#  