services:
  edulution-mail:
    image: ghcr.io/edulution-io/edulution-mail
    container_name: edulution-mail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/docker/edulution-mail:/srv/docker/edulution-mail
    environment:
      - MAILCOW_HOSTNAME=<YOUR_HOSTNAME>
      - MAILCOW_PATH=/srv/docker/edulution-mail
      - KEYCLOAK_SECRET_KEY=<YOUR_KEYCLOAK_SECRET_KEY>
